import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { NavbarGate } from "./components/navbar-gate";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Editorial display serif for v2 headings. One weight + italic; never faux-bold.
const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Syed Monis Sarwar - Portfolio",
  description: "Generated by Syed Monis Sarwar",
  metadataBase: new URL("https://syedmonissarwar.com"),
  alternates: {
    types: {
      "application/rss+xml": [
        { url: "/feed.xml", title: "Syed Monis Sarwar · RSS Feed" },
      ],
    },
  },
  openGraph: {
    title: "Syed Monis Sarwar",
    description: "Full Stack Back-end Developer Portfolio",
    url: "https://syedmonissarwar.com",
    siteName: "Syed Monis Sarwar",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Syed Monis Sarwar",
    description: "Full Stack Back-end Developer Portfolio",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <NavbarGate />
          {children}
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
